# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2b31b86bdf11adc95b44b87a42406a60c44e6002bd9eef0c707cdde0affde735f307c9cf6f458770a86a93ac334ddc1bab2a033daa8c900ddf2b1f727b83b76

test:
  secret_key_base: c32ccff14f4f9fd0b135ddc41ef846d3dae01533f8861cbc352d2a15236db07981d6e12636b7a98748ab40edb498ec86a3b91c0c3f9f7cd6d9678b13af205b8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
