# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84e4eba95b2c792f5fd604399a70001e4f1a1a9f41e86bccfaa5a0129dcd8eba03b98e72f62c3087461e5708d14b4c682fc14b10bf149faa5f2ff02a52ed6376

test:
  secret_key_base: b95d6826eecdd8938c355012a5653bf73c66a5b3a3116bbded4c4f704cb65390a108af3f35bf3853b0a463810c51a0d173f09505316d5ea9152a932810ec73f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
